general {
    hide_cursor = true
    immediate_render = true
}

background {
    monitor =
    color = rgb(2d353b)
}

input-field {
    monitor =
    size = 280, 56
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.25
    dots_center = true
    outer_color = rgb(a7c080)
    inner_color = rgb(343f44)
    font_color = rgb(d3c6aa)
    fade_on_empty = false
    placeholder_text = <span foreground="##d3c6aa">Password...</span>
    hide_input = false
    position = 0, 50
    halign = center
    valign = bottom
}
