# Preload the image into RAM
preload = /home/urahara/Desktop/Wallpapers/unsorted/your_image.png

# Apply to all monitors
wallpaper = , /home/urahara/Desktop/Wallpapers/unsorted/your_image.png

# Disable splash text overlay
splash = false
