general {
    lock_cmd = pidof hyprlock || hyprlock       # avoids starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display after resume
}

# 1. Dim screen brightness after 2.5 minutes (150s)
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# 2. Lock screen after 5 minutes (300s)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 3. Turn off screen (DPMS) after 10 minutes (600s)
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 4. Suspend system after 30 minutes (1800s)
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
